<Apples>:
    name: 'Apples'
    MDLabel:
        text: 'Apples'
    MDTextButton:
        text: 'Back to home'
        on_press:
            root.manager.transition.direction = 'right'
            root.manager.current = 'Plants_Home'

<Carrots>:
    name: 'Carrots'
    MDLabel:
        text: 'Carrots'
    MDTextButton:
        text: 'Back to home'
        on_press:
            root.manager.transition.direction = 'right'
            root.manager.current = 'Plants_Home'
